import fluffbox.rwx.Store
import fluffbox.rwx.Kiosk
import fluffbox.rwx.Speaker

class BootStrap {

    def init = { servletContext ->

      new Store(name: "Walgreens").save()
new Kiosk(store: Store.findByName("Walgreens"), inside: true, address: "3895 W Broward Blvd",
          city: "Ft Lauderdale", state:"FL", zipCode:"33312-1017").save()
new Store(name: "Winn Dixie").save()
new Kiosk(store: Store.findByName("Winn Dixie"), inside: false, address: "1531 N State Road 7",
          city: "Lauderhill", state:"FL", zipCode:"33313-5807").save()
new Kiosk(store: Store.findByName("Winn Dixie"), inside: false, address: "3800 N Ocean Blvd",
          city: "Fort Lauderdale", state:"FL", zipCode:"33308-6432").save()
new Store(name: "Albertsons").save()
new Kiosk(store: Store.findByName("Albertsons"), inside: true, address: "950 E Commercial Blvd",
          city: "Oakland Park", state:"FL", zipCode:"33334-3210").save()
new Kiosk(store: Store.findByName("Walgreens"), inside: true, address: "601 E Commercial Blvd",
          city: "Oakland Park", state:"FL", zipCode:"33334-3239").save()
new Store(name: "Walmart").save()
new Kiosk(store: Store.findByName("Walmart"), inside: true, address: "3001 N State Rd 7",
          city: "Lauderdale Lakes", state:"FL", zipCode:"33313-1913").save()
new Kiosk(store: Store.findByName("Winn Dixie"), inside: false, address: "3116 W Commercial Blvd",
          city: "Fort Lauderdale", state:"FL", zipCode:"33309-3415").save()
new Store(name: "Walmart Neighborhood Markets").save()
new Kiosk(store: Store.findByName("Walmart Neighborhood Markets"), inside: true, address: "1199 S Federal Hwy",
          city: "Pompano Beach", state:"FL", zipCode:"33062-7067").save()
new Store(name: "Exxon Mobil").save()
new Kiosk(store: Store.findByName("Exxon Mobil"), inside: true, address: "2399 S University Dr",
          city: "Davie", state:"FL", zipCode:"33324-5844").save()
new Kiosk(store: Store.findByName("Walgreens"), inside: true, address: "3015 S University Dr",
          city: "Davie", state:"FL", zipCode:"33328-2013").save()
new Kiosk(store: Store.findByName("Exxon Mobil"), inside: true, address: "1799 N University Dr",
          city: "Plantation", state:"FL", zipCode:"33322-4111").save()
new Kiosk(store: Store.findByName("Walmart"), inside: true, address: "2300 W Atlantic Blvd",
          city: "Pompano Beach", state:"FL", zipCode:"33069-2655").save()
new Kiosk(store: Store.findByName("Walgreens"), inside: true, address: "7105 W McNab Rd",
          city: "North Lauderdale", state:"FL", zipCode:"33068-5492").save()
new Kiosk(store: Store.findByName("Walmart"), inside: true, address: "3306 N University Dr",
          city: "Sunrise", state:"FL", zipCode:"33351").save()
new Kiosk(store: Store.findByName("Walmart"), inside: true, address: "7300 W McNab Rd",
          city: "North Lauderdale", state:"FL", zipCode:"33068-5481").save()
new Kiosk(store: Store.findByName("Walmart"), inside: true, address: "1885 N Pine Island Rd",
          city: "Plantation", state:"FL", zipCode:"33322-5208").save()
new Kiosk(store: Store.findByName("Walgreens"), inside: true, address: "6817 Taft St",
          city: "Hollywood", state:"FL", zipCode:"33024-5601").save()

      new Speaker(name:"Aaron Bedra", title:"Principal at Relevance, Member Clojure/core", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/36625_Bedra_medium.jpg", bio:"""Aaron Bedra is a principal at Relevance, Inc. (http://thinkrelevance.com) where he works as a technical lead, speaker, and author. Aaron's current focus is Enterprise Systems Integration using Clojure and JRuby. He is the maintainer of the Ruby code coverage analysis tool, RCov, and is a contributor to many open source projects including the Clojure language, Clojure Contrib, Compojure, and Ruby on Rails. Aaron is the author of the Rails Security Audit Peepcode.""").save()

new Speaker(name:"Aleksandar Seovic", title:"Software Developer and Author", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/34212_Seovic_medium.jpg", bio:"""Aleksandar Seovi? is founder and managing director at S4HC, Inc., where he leads professional services practice. He works with customers throughout the world to help them implement innovative solutions to complex business and technical problems.Aleksandar lead the implementation of Oracle Coherence for .NET, a client library that allows applications written in any .NET language to access data and services provided by Oracle Coherence data grid. He was also one of the key people involved in the design and implementation of Portable Object Format (POF), a platform-independent object serialization format that allows seamless interoperability of Coherence-based Java, .NET and C++ applications.Aleksandar is the author of Oracle Coherence 3.5 (Packt Publishing, 2010) and Oracle ACE Director for Fusion Middleware. He frequently speaks about and evangelizes Coherence at conferences, Java and .NET user group events, and Coherence SIGs.""").save()

new Speaker(name:"Alex Miller", title:"Sr. Engineer with Terracotta Inc.", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/6938_Miller_medium.jpg", bio:"""Alex Miller is a Sr. Engineer with Terracotta Inc, the makers of the open-source Java clustering product Terracotta. Prior to Terracotta, Alex worked at BEA Systems on the AquaLogic product line and was Chief Architect at MetaMatrix. His interests include Java, concurrency, distributed systems, query languages, and software design. Alex enjoys writing his blog at http://tech.puredanger.com and has spoken at a number of Java user group meetings and conferences.In St. Louis, Alex is responsible for founding the Lambda Lounge, a user group for the study of functional and dynamic languages.""").save()

new Speaker(name:"Andrew Glover", title:"Founder of easyb", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/32_Glover_medium.jpg", bio:"""Andrew is the founder of the easyb BDD framework and the co-author of Addison Wesley's "Continuous Integration", Manning's "Groovy in Action" and "Java Testing Patterns". He is an author for multiple online publications including IBM's developerWorks and Oreilly's ONJava and ONLamp portals. He actively blogs about software at thediscoblog.com.""").save()

new Speaker(name:"Ari Zilka", title:"CTO and Co-Founder, Terracotta, Inc.", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/10391_Zilka_medium.jpg", bio:"""Ari Zilka founded Terracotta in 2003 and is the company?s Chief Technology Officer. Combining business and technology leadership, Ari was an Entrepreneur-in-Residence at Accel Partners and worked at PriceWaterhouseCoopers with some of the world?s leading brands. He was Chief Architect at Walmart.com where he built and led a team of core engineers. And in the mid 1990s, Ari invented a new object relational database that still exceeds the capabilities and performance of database technology today""").save()

new Speaker(name:"Ben Rady", title:"Author, Creator of Infinitest", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/7260_Rady_medium.jpg", bio:"""Ben is a passionate and pragmatic software developer. He is the creator of Infinitest, a continuous test runner for JUnit. Ben is the author of two books on the topic of CT: "Continuous Testing in Ruby" and "Continuous Testing in Java", both soon to be published with the Pragmatic Bookshelf. He also contributes to a number of other projects that benefit the open source community, and regularly speaks at conferences and user groups around the country.Presently employed as a Senior Software Engineer at DRW Trading Group, Ben is focused on helping teams improve their development practices to support rapid and regular delivery of well crafted software.""").save()

new Speaker(name:"Brian Gilstrap", title:"Brian Gilstrap - Principal Software Engineer at Object Computing, Inc.", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/36484_Gilstrap_medium.jpg", bio:"""Brian Gilstrap is a Principal Software Engineer at Object Computing, Inc. where he has spent the last eleven of his 20+ years in the industry. In those years, he has worked with many languages and many technologies. He writes and blogs frequently, and has been on the steering committee of the St. Louis Java User's Group more than a decade. With OCI he provides consulting to companies in many industries and countries, and develops & delivers training courses for Washington University's Center for Applied Information Technology.Brian has a passion for building software that is easy to use and robust while still meeting the rapid development requirements in today's industry. He has expertise in distributed systems, object oriented analysis and design, secure computing, and many languages and frameworks.""").save()

new Speaker(name:"Brian Goetz", title:"Author of Java Concurrency in Practice", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/24_Goetz_medium.jpg", bio:"""Brian Goetz has been a professional software developer for 20 years. He is the author of over 75 articles on software development, and his book, Java Concurrency In Practice, was published in May 2006 by Addison-Wesley. He serves on the JCP Expert Groups for JSRs 166 (concurrency utilities), 107 (caching), and 305 (annotations for safety analysis). He is a frequent presenter at JavaOne, OOPSLA, JavaPolis, SDWest, and the No Fluff Just Stuff Software Symposium Tour. Brian is a Sr. Staff Engineer at Sun Microsystems.""").save()

new Speaker(name:"Brian Sam-Bodden", title:"Java author, Ruby geek and Open Source Advocate", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/28_Sam-Bodden_medium.jpg", bio:"""Brian Sam-Bodden is an author and recognized international speaker that has spent over twelve years working with object technologies, with an emphasis on the Java platform and in recent times falling in love with Ruby. He holds dual bachelor degrees from Ohio Wesleyan University in computer science and physics and is the president and chief software architect for Integrallis http://www.integrallis.com, where he focuses on building great applications with Java and Ruby. Brian has worked as an architect, developer, mentor, and trainer for several Fortune 500 companies in the tax, insurance, retail sciences, telecommunications, distribution, banking, finance, aviation, and scientific data management industries. As an independent consultant, he has promoted the use of open source in the industry by educating his clients on the cost benefits and productivity gains they can achieve. He is a frequent speaker at user groups and conferences nationally and abroad. Brian is the author of "Beginning POJOs: Spring, Hibernate, JBoss and Tapestry" and has also co-authored the Apress Java title "Enterprise Java Development on a Budget: Leveraging Java Open Source Technologies".""").save()

new Speaker(name:"Brian Sletten", title:"Forward Leaning Software Engineer", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/22_Sletten_medium.jpg", bio:"""Brian Sletten is a liberal arts-educated software engineer with a focus on forward-leaning technologies. He has a background as a system architect, a developer, a mentor and a trainer. His experience has spanned the online games, defense, finance and commercial domains with security consulting, network matrix switch controls, 3D simulation/visualization, Grid Computing, P2P and Semantic Web-based systems. He has a B.S. in Computer Science from the College of William and Mary. He is President of Bosatsu Consulting, Inc. and lives in Los Angeles, CA.He focuses on web architecture, resource-oriented computing, social networking, the Semantic Web, scalable systems, security consulting and other technologies of the late 20th and early 21st Centuries.""").save()

new Speaker(name:"Burr Sutter", title:"Software Architect", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/526_Sutter_medium.jpg", bio:"""Burr Sutter is a current Sun Java Champion, President of the Atlanta Java Users Group and President of the Atlanta Chapter of theInternational Association of Software Architects. He has over 15 years of software design and development experience along with numerous published articles, book chapters and developer conference speaking engagements. He is presently employed at JBoss, a division of Red Hat.""").save()

new Speaker(name:"Chris Maki", title:"Principal Engineer at Overstock.com, author JPA 101: Java Persistence Explained", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/6749_Maki_medium.jpg", bio:"""Chris Maki is a Principal Software Engineer at Overstock.com. Before joining Overstock.com, Chris was an independent consultant specializing in server-side Java development. He has been designing and building server-side systems for 15 years in C++, Objective-C, and Java.Chris spent many years working as an enterprise architect specializing in large-scale Java system design and development. In addition to being a Java evangelist, he is an avid proponent of Agile Software Development.Chris is the President of the Utah Java User Group and a member of the WebBeans expert group (JSR-299) and the JPA 2.0 expert group (JSR-317). He is also the author of JPA 101: Java Persistence Explained.""").save()

new Speaker(name:"Chris Richardson", title:"Author of POJOs in Action", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/985_Richardson_medium.jpg", bio:"""Chris Richardson is a developer, architect and mentor with over 20 years of experience and is the author of the recently published book "POJOs in Action". He runs a consulting company that helps development teams become more productive and successful by adopting POJOs and lightweight frameworks. Chris has been a technical leader at a variety of companies including Insignia Solutions and BEA Systems. Chris has a computer science degree from the University of Cambridge in England. He lives in Oakland, CA with his wife and three children.""").save()

new Speaker(name:"Craig Walls", title:"Author of Spring in Action", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/38_Walls_medium.jpg", bio:"""Craig Walls has been professionally developing software for over 16 years (and longer than that for the pure geekiness of it). He is a senior engineer with SpringSource and is the author of Modular Java (published by Pragmatic Bookshelf) and Spring in Action and XDoclet in Action (both published by Manning). He's a zealous promoter of the Spring Framework, speaking frequently at local user groups and conferences and writing about Spring and OSGi on his blog. When he's not slinging code, Craig spends as much time as he can with his wife, two daughters, 5 birds and 3 dogs.""").save()

new Speaker(name:"Dan Allen", title:"Senior Software Engineer - JBoss by Red Hat, Author, Open Source Advocate", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/5206_Allen_medium.jpg", bio:"""Dan Allen is a member of the Seam and Web Beans project teams at JBoss by Red Hat, author of Seam in Action and a frequent speaker at major industry conferences such as JavaOne, Devoxx, TSSJS, Jazoon and JSFOne. Dan is known for his passionate work, with nearly a decade of development experience using technologies that include Java frameworks (Seam, JSF, EJB3, Hibernate, Spring, Struts), testing frameworks (JUnit, TestNG), JavaScript and DOM scripting, CSS and page layouts, Maven 2, Ant, Groovy, and many others.Quickly after graduating from college, Dan became captivated by the world of free and open source software (FOSS). His involvment in FOSS helped him transition into the software development industry. He soon discovered the combination of Linux and the Java EE platform to be the ideal blend on which to build his professional career. In his search for a robust Web framework, Dan discovered JBoss Seam, which was quickly granted this most coveted spot in his development toolbox. The rest, as they say, is history. Dan is also a dedicated open source and Linux advocate and blogs about his experiences regularly. You can keep up with his discoveries by subscribing to his blog at http://mojavelinux.com.""").save()

new Speaker(name:"Dan Juengst", title:"Sr. Director of Engineering for Terracotta", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/42129_Juengst_medium.jpg", bio:"""As Sr. Director of World Wide Field Engineering for Terracotta, Dan leads a world-class technical team that helps enterprise IT organizations improve their service availability and application performance through the application of the industry leading Terracotta Java Scalability Technology. Prior to Terracotta, Dan served as VP of Technical Services for CA?s Wily Application Performance Management business. During his tenure at CA Wily, Dan helped many Fortune 500 and Global 2000 companies manage the performance of their mission-critical Web Applications. Previously, Dan worked at Sun Microsystems and Silicon Graphics Computer Systems (SGI) helping customers optimize the performance of their software applications in supercomputing and grid-computing environments. Dan?s roots in high performance computing originated in his work in applying Computational Fluid Dynamics techniques to hypersonic air vehicle design at Lockheed-Martin and Boeing.""").save()

new Speaker(name:"Dave Klein", title:"Author of 'Grails: A Quick-Start Guide'", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/2412_Klein_medium.jpg", bio:"""Dave is a consultant helping organizations of all sizes to develop applications more quickly (and have more fun doing it) with Grails. Dave has been involved in enterprise software development for the past 15 years. He has worked as a developer, architect, project manager, mentor and trainer. Dave has presented at user groups and national conferences. He is also the founder of the Capital Java User Group in Madison, Wisconsin, the Gateway Groovy Users in St. Louis, MO, and the author of Grails: A Quick-Start Guide, published by the Pragmatic Programmers. . Dave's Groovy and Grails related thoughts can be found at http://dave-klein.blogspot.com""").save()

new Speaker(name:"David Bock", title:"Principal Consultant, CodeSherpas Inc.", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/34_Bock_medium.jpg", bio:"""David Bock is a Principal Consultant at CodeSherpas, a company he founded in 2007. Mr. Bock is also the President of the Northern Virginia Java Users Group, the Editor of O'Reilly's OnJava.com website, and a frequent speaker on technology in venues such as the No Fluff Just Stuff Software Symposiums.In January 2006, Mr. Bock was honored by being awarded the title of Java Champion by a panel of esteemed leaders in the Java Community in a program sponsored by Sun. There are approximately 100 active Java Champions worldwide.David has also served on several JCP panels, including the Specification of the Java 6 Platform and the upcoming Java Module System.In addition to his public speaking and training activities, Mr. Bock actively consults as a software engineer, project manager, and team mentor for commercial and government clients.""").save()

new Speaker(name:"David Hussman", title:"Agility Coach/Instructor/Practioner", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/23_Hussman_medium.jpg", bio:"""David teaches and coaches the adoption and improvement of agility as a delivery tool. His work includes helping companies of all sizes all over the world. Sometimes he is pairing with developers and testers, while other times he is helping to invent, evolve and plan the delivery of all types of products and projects. David also spends a great deal of time helping leaders at all levels find ways to pragmatically use agility to foster innovation.Prior to working as a full time coach, David spent years building software in a variety of domains: digital audio, digital biometrics, medical, financial, retail, and education to name a few. David now leads DevJam, a company composed of agile collaborators. As mentors and practitioners, DevJam focuses on agility as a tool to help people and companies improve their software production skills. DevJam provides seasoned leaders that strive to pragmatically match technology, people, and processes to create better and cooler products in competitive cycles.Along with teaching and coaching, David participates in conferences around the world. He is the recipient of the Agile Alliance, 2009 Gordon Pask Award. David continuously contributes to books and various publications.For coaching information, presentations, and more, visit www.devjam.com""").save()

new Speaker(name:"Esther Derby", title:"Co-author of \"Behind Closed Doors: Secrets of Great Management\"", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/15419_Derby_medium.jpg", bio:"""Esther works with individuals, teams, and managers to improve their ability to deliver valuable software. Esther is recognized as a leader in the human-side of software development, including management, systems-thinking, organizational change, collaboration, team building, facilitation and retrospectives.She?s been a programmer, system manager, manager and internal consultant. Since 1997, she?s run her own consulting firm, esther derby associates, inc., in Minneapolis, MN. Her clients include small niche firms, mid-size companies and Fortune 500 companies. She?s worked in financial services, insurance, health care and manufacturing as well as in product and software-as-a-service companies.Esther is the author of over 100 articles, and co-author of Agile Retrospectives: Making Good Teams Great and Behind Closed Doors: Secrets of Great Management. She?s written widely on the topic of management, leadership, collaboration and change as they relate to companies adopting (or considering) Agile Methods, including Three Pillars of Executive Support for Agile Adoption (Agile Journal), Achieving Agility: Means to an End or End in Itself? (insights), and What?s a Manager to Do? (Better Software Magazine).Esther is a sought after teacher and speaker. She?s given talks and workshops in the US, Europe, China, India, and New Zealand.She?s a founder of the AYE Conference, and is serving her second term as a member of the Board of Directors for the Agile Alliance. She also was one of the three original founders of the Scrum Alliance.Esther has an MA in Organizational Leadership and a certificate in Human System Dynamics.Esther can be reached at (612) 724-8114, or by email.Take a look at www.estherderby.com for more of Esther?s writing, or follow her on Twitter @estherderby""").save()

new Speaker(name:"Hans Dockter", title:"Founder of Gradle and CEO of Gradle Inc.", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/29446_Dockter_medium.jpg", bio:"""Hans Dockter is the founder and project lead of the Gradle build system and the CEO of Gradle Inc, a company that provides training, support and consulting for Gradle and all forms of enterprise software project automation in general.Hans has 13 years of experience as a software developer, team leader, architect, trainer, and technical mentor. Hans is a thought leader in the field of project automation and has successfully been in charge of numerous large-scale enterprise builds. He is also an advocate of Domain Driven Design, having taught classes and delivered presentations on this topic together with Eric Evans. In the earlier days, Hans was also a committer for the JBoss project and founded the JBoss-IDE.""").save()

new Speaker(name:"Howard Lewis Ship", title:"Creator of Apache Tapestry", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/31_Lewis_Ship_medium.jpg", bio:"""Howard Lewis Ship is the creator and lead developer for the Apache Tapestry project, and is a noted expert on Java framework design and developer productivity. He has over twenty years of full-time software development under his belt, with over ten years of Java. He cut his teeth writing customer support software for Stratus Computer, but eventually traded PL/1 for Objective-C and NeXTSTEP before settling into Java. Lately, he's been dipping his toes into alternate languages, including Clojure.Howard is the author of Tapestry in Action for Manning Publications (which covers Tapestry 3.0). He lives in Portland, Oregon with his wife Suzanne, a novelist, and his son, Jacob.Howard is an independent consultant, offering Tapestry training, mentoring and project work as well as training in Clojure.""").save()

new Speaker(name:"James Carr", title:"NodeJS Expert", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/4170_Carr_medium.jpg", bio:"""James is a contractor in the St.Louis area that shares a passion for software craftsmanship and has enjoyed software development since he wrote his first program in Basic on the Tandy Color Computer 3 way back in 1988.In addition to a passion for technology, he also has a keen interest in improving teamwork and collaboration through interactive activities to get people thinking creatively and develop stronger, richer communication channels with their stakeholders.""").save()

new Speaker(name:"Jeff Brown", title:"Core Member of the Grails Development Team", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/4133_Brown_medium.jpg", bio:"""Core member of the Grails development team, Jeff Brown, is a Senior Software Engineer with SpringSource. Jeff has been involved in designing and building object oriented systems for over 15 years. Jeff's areas of expertise include web development with Groovy & Grails, Java and agile development.""").save()

new Speaker(name:"Jeremy Deane", title:"Director of Research & Architecture", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/20924_Deane_medium.jpg", bio:"""Jeremy Deane has over 15 years of software engineering experience in leadership positions. His expertise includes Enterprise Integration Architecture, Web Application Architecture, and Software Process Improvement. In addition, he is an accomplished speaker and technical author.""").save()

new Speaker(name:"Johanna Rothman", title:"Speaker, Consultant, author for managing product development", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/15415_Rothman_medium.jpg", bio:"""Johanna Rothman helps managers and leaders solve problems and seize opportunities.She consults, speaks, and writes on managing high-technology product development. She enables managers, teams, and organizations to become more effective by applying her pragmatic approaches to the issues of project management, risk management, and people management.Johanna writes two blogs: Managing Product Development and Hiring Technical People. She is the author of:- Manage Your Project Portfolio: Increase Your Capacity and Finish More Projects.- 2008 Jolt Productivity award winning Manage It! Your Guide to Modern, Pragmatic Project Management- Behind Closed Doors: Secrets of Great Management (with Esther Derby)- Hiring the Best Knowledge Workers, Techies & Nerds: The Secrets and Science of Hiring Technical PeopleFind more of Johanna's articles and her blogs at www.jrothman.com.""").save()

new Speaker(name:"Keith Donald", title:"SpringSource Principal & Founding Partner", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/27_Donald_medium.jpg", bio:"""Keith Donald is a principal and founding partner at SpringSource, the company behind Spring and a division of VMware. At SpringSource, Keith is a full-time member of the Spring development team focusing on web application development productivity. He is also the architect behind SpringSource's state-of-the-art training curriculum, which has provided practical Spring training to over 10,000 students worldwide.Over his career, Keith, an experienced enterprise software developer and mentor, has built business applications for customers spanning a diverse set of industries including banking, network management, information assurance, education, retail, and healthcare. He is particularly skilled at translating business requirements into technical solutions.""").save()

new Speaker(name:"Ken Sipe", title:"Technology Director, Perficient, Inc. (PRFT)", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/4142_Sipe_medium.jpg", bio:"""Ken Sipe is a Technology Director with Perficient, Inc. (PRFT), IBM's largest service partner, where he leads multiple teams in the development of solutions in the SOA, Web 2.0 and portal domains, on both the Java and .Net platforms.Ken was the founder of CodeMentor, where he was the Chief Architect and Mentor, leading clients in the execution of RUP and Agile methodologies in the delivery of software solutions.Ken has a deep need to be highly diversified. Ken often works with IT executives on high-level strategic roadmaps, currently geared around service oriented architectures (SOA). Ken also likes to keep his hands "dirty" in the code, which has him on a regular basis, pairing or otherwise producing code. Ken is regularly requested by clients that know him to "rescue" projects, either through the streamlining of processes or the rapid production of code.""").save()

new Speaker(name:"Kenneth Kousen", title:"President of Kousen IT, Inc.", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/848_Kousen_medium.jpg", bio:"""Ken Kousen is the President of Kousen IT, Inc., through which he does technical training, mentoring, and consulting in all areas of Java and XML. He is the author of the upcoming book about Java/Groovy integration, entitled "Java and Groovy: The Sweet Spots", from Manning.He has been a tech reviewer for several books on software development. Over the past decade he's taught thousands of developers in business and industry. He is also an adjunct professor at the Rensselaer Polytechnic Institute site in Hartford, CT. His academic background includes two BS degrees from M.I.T., an MS and a Ph.D. from Princeton, and an MS in Computer Science from R.P.I.""").save()

new Speaker(name:"Mark Johnson", title:"Director of Consulting at CGI", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/2816_Johnson_medium.jpg", bio:"""Mark Johnson is Director of Consulting at CGI where he focuses on raising the development bar so projects are brought in on time and under budget. Most important of all the project needs to be delivered to the customer's satisfaction.Mark has worked on a wide range of technology during his career. Most recently he has focused on Groovy, Grails, and Seam as technologies which enable high quality applications quickly.Mark is active in the software community as the President of the New England Java Users Group (NEJUG). When not working, Mark can be found riding his mountain bike on local trails and playing with his family.""").save()

new Speaker(name:"Mark Richards", title:"SOA and Integration Architect, Author of Java Message Service", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/35_Richards_medium.jpg", bio:"""Mark Richards is a Director and Senior Architect at Collaborative Consulting, LLC, a Boston-based Business and Architecture Consulting Firm, where he is involved in the architecture, design, and implementation of SOA, EDA, messaging, and other architectures, primarily in the Java platform. Prior to joining Collaborative Mark was an Executive IT Architect with IBM, where he worked as an SOA and enterprise architect in the financial services area. He has been involved in the software industry since 1984 and has many battle scars to show for it. Mark served as the President of the Boston Java User Group in 1997 and 1998, and the President of the New England Java Users Group from 1999 thru 2003. Mark is the author of the book Java Message Service (2nd edition) from O'Reilly. He is also the author of Java Transaction Design Strategies, contributing author of the book 97 Things Every Software Architect Should Know from O'Reilly, contributing author of NFJS Anthology Volume 1, and contributing author of NFJS Anthology Volume 2. Mark has many architect and developer certifications, including those from IBM, Sun, The Open Group, and Oracle. He is a regular conference speaker at the No Fluff Just Stuff Symposium Series and speaks at other conferences and user groups around the world. When he is not working Mark can usually be found hiking with his wife and two daughters in the White Mountains or along the Appalachian Trail.""").save()

new Speaker(name:"Mark Volkmann", title:"Software Consultant and Partner at OCI", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/842_Volkmann_medium.jpg", bio:"""Mark Volkmann has been a software consultant for Object Computing, Inc. (OCI) in St. Louis since 1996. He has been developing software in Java since 1995.Mark has created and teaches many courses in Java, XML and Ruby. They include: Introduction to Java, Java Syntax for Non-C Programmers, Java Programming, Advanced Java Programming, Creating Graphical User Interfaces Using Java (Swing), eXtensible Markup Language (XML), XML Programming Using Java and Web Services Using Java, and Ruby Programming.Mark is a member of the St. Louis Java User Group steering committee and a regular presenter for that group. He has written for XML Journal. Mark has also presented at XML DevCon conferences, No Fluff Just Stuff Java symposiumsand the St. Louis Ruby User Group.""").save()

new Speaker(name:"Matt Stine", title:"Software Development Group Leader, St. Jude Children's Research Hospital", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/29510_Stine_medium.jpg", bio:"""Matt is the Group Leader of Research Application Development in the Research Informatics Division of Information Sciences at St. Jude Children's Research Hospital in Memphis, Tennessee. Matt has been developing and supporting enterprise Java applications in support of life sciences research for St. Jude since 2001. Matt is a committer to multiple open source projects and is the founding member of the Memphis/Mid-South Java User Group. Matt is also the Zone Leader at http://agile.dzone.com, and his articles have also appeared in GroovyMag and NFJS the Magazine. His current areas of interest include lean/agile software development, modularity and OSGi, mobile application development (iPhone/iPad/Android), web development (HTML5, etc.), and Groovy/Grails.""").save()

new Speaker(name:"Matthew McCullough", title:"Open Source Architect, Ambient Ideas", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/9793_McCullough_medium.jpg", bio:"""Matthew McCullough is an energetic 12 year veteran of enterprise software development, open source education, and co-founder of Ambient Ideas, LLC, a Denver consultancy. Matthew currently is a member of the JCP, reviewer for technology publishers including O'Reilly, author of the DZone Maven RefCard, and President of the Denver Open Source Users Group. His experience includes successful J2EE, SOA, and Web Service implementations for real estate, financial management, and telecommunications firms, and several published open source libraries.Matthew jumps at opportunities to evangelize and educate teams on the benefits of open source. His current interests are Cloud Computing, Maven, iPhone, Distributed Version Control, and OSS Tools.Matthew resides in Denver with his beautiful wife and baby daughter, who all are active in nearly every outdoor activity Colorado offers.""").save()

new Speaker(name:"Michael Easter", title:"Software Composer", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/37251_Easter_medium.jpg", bio:"""Michael Easter has been a consultant with Advantage Consulting in St Louis since 2006, and has been a professional developer for 16 years. Immersed primarily within Java technology, he enjoys frequent excursions into other languages such as Groovy and Haskell. He holds an M.Math. from the University of Waterloo in Computer Science.""").save()

new Speaker(name:"Michael Nygard", title:"Agile technology leader and dynamicist", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/5145_Nygard_medium.jpg", bio:"""Michael strives to raise the bar and ease the pain for developers across the country. He shares his passion and energy for improvement with everyone he meets, sometimes even with their permission. Michael has spent the better part of 20 years learning what it means to be a professional programmer who cares about art, quality, and craft. He's always ready to spend time with other developers who are fully engaged and devoted to their work--the "wide awake" developers. On the flip side, he cannot abide apathy or wasted potential.Michael has been a professional programmer and architect for nearly 20 years. During that time, he has delivered running systems to the U. S. Government, the military, banking, finance, agriculture, and retail industries. More often than not, Michael has lived with the systems he built. This experience with the real world of operations changed his views about software architecture and development forever.He worked through the birth and infancy of a Tier 1 retail site and has often served as "roving troubleshooter" for other online businesses. These experiences give him a unique perspective on building software for high performance and high reliability in the face of an actively hostile environment.Most recently, Michael wrote "Release It! Design and Deploy Production-Ready Software", a book that realizes many of his thoughts about building software that does more than just pass QA, it survives the real world. Michael previously wrote numerous articles and editorials, spoke at Comdex, and co-authored one of the early Java books.""").save()

new Speaker(name:"Nathaniel Schutta", title:"Author, speaker, software engineer focused on user interface design.", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/1314_Schutta_medium.jpg", bio:"""Nathaniel T. Schutta is a senior software engineer focussed on making usable applications. A proponent of polyglot programming, Nate has written two books on Ajax and speaks regularly at various worldwide conferences, No Fluff Just Stuff symposia, universities, and Java user groups. In addition to his day job, Nate is an adjunct professor at the University of Minnesota where he teaches students to embrace dynamic languages.""").save()

new Speaker(name:"Neal Ford", title:"Application Architect at ThoughtWorks, Inc.", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/21_Ford_medium.jpg", bio:"""Neal is Software Architect and Meme Wrangler at ThoughtWorks, a global IT consultancy with an exclusive focus on end-to-end software development and delivery.Before joining ThoughtWorks, Neal was the Chief Technology Officer at The DSW Group, Ltd., a nationally recognized training and development firm. Neal has a degree in Computer Science from Georgia State University specializing in languages and compilers and a minor in mathematics specializing in statistical analysis.He is also the designer and developer of applications, instructional materials, magazine articles, video presentations, and author of 6 books, including the most recent The Productive Programmer. His language proficiencies include Java, C#/.NET, Ruby, Groovy, functional languages, Scheme, Object Pascal, C++, and C. His primary consulting focus is the design and construction of large-scale enterprise applications. Neal has taught on-site classes nationally and internationally to all phases of the military and to many Fortune 500 companies. He is also an internationally acclaimed speaker, having spoken at over 100 developer conferences worldwide, delivering more than 600 talks. If you have an insatiable curiosity about Neal, visit his web site at http://www.nealford.com. He welcomes feedback and can be reached at nford@thoughtworks.com.""").save()

new Speaker(name:"Paul Rayner", title:"Agile Consultant, Developer and Architect for Virtual Genius LLC", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/15893_Rayner_medium.jpg", bio:"""Paul Rayner is a Denver-based independent consultant with more than twenty years of software development and consulting experience. His company, Virtual Genius LLC, provides organizations with the tools and practices needed to succeed at agile software development, from portfolio management through to customer delivery. He specializes in helping organizations struggling with their transition to agile software development, or in need of external agile custom development and architectural expertise.Paul is the founder and president of IASA Denver, a member of the Agile Denver leadership, and speaks regularly at user groups and conferences. He writes with an Australian accent about software development at www.virtual-genius.com/blog.""").save()

new Speaker(name:"Peter Bell", title:"Expert in Domain Specific Languages", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/26712_Bell_medium.jpg", bio:"""Peter Bell has been presenting internationally for years on Domain Specific Languages, Domain Specific Modeling and Software Product Lines. His focus is on getting beyond the syntax to handle the engineering concerns when developing real world DSL solutions - from evolution to IDE support, constraint checking, documentation and testing DSLs.He is on the Program Committee for Code Generation in Cambridge England and the Domain Specific Modeling workshop at SPLASH (was ooPSLA).He is also the CEO/CTO of SystemsForge - a New York based company that uses DSLs and a Software Product Line built on top of Groovy and Grails to develop custom web applications quickly and cost effectively. The SystemsForge product line has been presented at ooPSLA and Code Generation and written up in IEEE Software and Methods & Tools.""").save()

new Speaker(name:"Pratik Patel", title:"Enterprise Architect", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/14890_Patel_medium.jpg", bio:"""Pratik Patel wrote the first book on 'enterprise Java' in 1996, "Java Database Programming with JDBC." He has also spoken at various conferences such as the Net Database Summit, WWW7 and the Atlanta Java User's Group (AJUG). Pratik currently runs the Atlanta Groovy and Grails User Group (ATL2G) as well as actively participating & presenting in the Atlanta Spring UG and Atlanta Java UG.Pratik's specialty is in large-scale Java applications for mission-critical use. He has designed and built enterprise applications in the retail, health care, financial services, and telecoms sectors. Pratik holds a master's in Biomedical Engineering from UNC, has worked in places such as New York, London, and Hong Kong, and currently lives in Atlanta, GA.""").save()

new Speaker(name:"Richard Worth", title:"Sr. Developer of jQuery UI", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/18860_Worth_medium.jpg", bio:"""Richard D. Worth is a UI developer in the Washington, DC area. He is one of the lead developers of jQuery UI, a component framework built on top of jQuery, designed to make Rich Internet Applications as simple as jQuery has made Ajax. Richard is also a co-author of the upcoming book 'jQuery Cookbook'.""").save()

new Speaker(name:"Robert Fischer", title:"Java Concurrency Specialist and GORM Expert; Principal, Smokejumper Consulting", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/20483_Fischer_medium.jpg", bio:"""Robert Fischer is a multi-language open source developer currently specializing in Groovy in Grails. In the past, his specialties have been in Perl, Java, Ruby, and OCaml. In the future, his specialty will probably be F# or (preferably) a functional JVM language like Scala or Clojure.Robert is the author of Grails Persistence in GORM and GSQL, a regular contributor to GroovyMag and JSMag, the founder of the JConch Java concurrency library, and the author/maintainer of Liquibase-DSL and the Autobase database migration plugin for Grails.""").save()

new Speaker(name:"Rohit Bhardwaj", title:"Principal Software Engineer, Kronos Inc Expert in agile development", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/15213_Bhardwaj_medium.jpg", bio:"""Rohit Bhardwaj is a Principal Software Engineer at Kronos Incorporated and has fifteen years of extensive experience in architecture, design and agile development. Rohit is an expert in application development in Service Oriented Architecture (SOA), REST, Cloud Computing, RIA, Android, Web Services and SOAPUI. Rohit is Sun Certified Java developer for Java 1.5 Platform. Rohit did his Masters in Computer Science from Boston University and Harvard University. He can be reached at rbhardwaj@kronos.com or using Twitter at rbhardwaj1""").save()

new Speaker(name:"Scott Davis", title:"Author of \"Groovy Recipes\" & TDD Expert", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/18_Davis_medium.jpg", bio:"""Scott Davis is the founder of ThirstyHead.com, a training company that specializes in Groovy and Grails training.Scott published one of the first public websites implemented in Grails in 2006 and has been actively working with the technology ever since. Author of the book Groovy Recipes: Greasing the Wheels of Java and two ongoing IBM developerWorks article series (Mastering Grails and in 2009, Practically Groovy), Scott writes extensively about how Groovy and Grails are the future of Java development.Scott teaches public and private classes on Groovy and Grails for start-ups and Fortune 100 companies. He is a regular presenter on the international technical conference circuit (including No Fluff Just Stuff). In 2008, Scott was voted the top Rock Star at JavaOne for his talk "Groovy, the Red Pill: How to blow the mind of a buttoned-down Java developer".""").save()

new Speaker(name:"Scott Leberknight", title:"Chief Architect at Near Infinity", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/646_Leberknight_medium.jpg", bio:"""Scott is Chief Architect at Near Infinity Corporation, an enterprise software development and consulting services company based in Reston, Virginia. He has been developing enterprise and web applications for 14 years professionally, and has developed applications using Java, Ruby, Groovy, and even an iPhone application with Objective-C. His main areas of interest include alternative persistence technologies, object-oriented design, system architecture, testing, and frameworks like Spring, Hibernate, and Ruby on Rails. In addition, Scott enjoys learning new languages to make himself a better and more well-rounded developer a la The Pragmatic Programmers' advice to "learn one language per year."Scott holds a B.S. in Engineering Science and Mechanics from Virginia Tech, and an M. Eng. in Systems Engineering from the University of Maryland. Scott speaks at the No Fluff Just Stuff Symposiums and various other conferences. In his (sparse) spare time, Scott enjoys spending time with his wife, three children, and cat. He also tries to find time to play soccer, go snowboarding, and mountain bike whenever he can.""").save()

new Speaker(name:"Srivaths Sankaran", title:"Sr. Java Consultant", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/20822_Sankaran_medium.jpg", bio:"""Sri Sankaran has been professionally developing software for over 15 years. During this time, he has designed and delivered solutions for clients in industries as varied as insurance, energy, telecom and the retail sector. Leveraging the breadth of this experience along with the depth of his knowledge of pertinent technologies such as Spring, Hibernate, Ajax, Java and Ruby on Rails allows him to choose the right combination of tools and techniques to solve his customers divergent needs.Over the years as a consultant he has been relied upon as the go-to person for matters of application architecture. Project managers look to his leadership and guidance in project estimation, staffing and delivery.When he is not working on software he spends time with his family of wife, daughter and dog. Oh, he is a rabid dog lover and would love to one day have a pack of dogs and raise them to be well balanced therapy animals.""").save()

new Speaker(name:"Stevie Borne", title:"Software Developer and Agile Coach", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/4991_Borne_medium.jpg", bio:"""Stevie has almost 15 years of software development experience, much of it in the healthcare industry. For the past 7 years she?s combined her development experience with agile coaching. She often works side-by-side next to members of the teams she coaches, including business users, testers, and developers. She has the unique ability to speak the language of business owners as well the technical language of developers. Her passion for mentoring teams toward agile adoption enables her to lead teams to understand and often exceed customer expectations. Stevie is a Certified Scrum Master, and her interests include Java UI development, automated testing, and always looking to how a team can improve their processes.In her spare time she enjoys spending time with her husband and two young children as well as competing in triathlons.""").save()

new Speaker(name:"Stuart Halloway", title:"CEO of Relevance", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/6_Halloway_medium.jpg", bio:"""Stuart Halloway is the CEO of Relevance, Inc. (www.thinkrelevance.com). With co-founder Justin Gehtland, Stuart helps companies adopt agile, as well as innovative technologies such as Clojure and Ruby on Rails. Stuart is the author of Programming Clojure, Rails for Java Developers, and Component Development for the Java Platform. Prior to founding Relevance, Stuart was the Chief Architect at Near-Time, and the Chief Technical Officer at DevelopMentor.""").save()

new Speaker(name:"Ted Neward", title:"Enterprise, Virtual Machine and Language Wonk", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/9_Neward_medium.jpg", bio:"""Ted Neward is the Principal with Neward & Associates, where he specializes in high-scale enterprise systems, working with clients ranging in size from Fortune 500 corporations to small 20-person shops. He speaks on the conference circuit, including the No Fluff Just Stuff Symposium tour, discussing Java, .NET and XML service technologies, focusing on Java-.NET interoperability, programming languages, and virtual machine technologies. He has written several widely-recognized books in both the Java and .NET space, including the recently-released "Effective Enterprise Java", and the forthcoming "Professional F#". He lives in the Pacific Northwest.""").save()

new Speaker(name:"Tiffany Lentz", title:"Principal Consultant & Program Manager with Thoughtworks", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/29664_Lentz_medium.jpg", bio:"""Tiffany Lentz, a Principal Consultant and Program Manager, is proudly employed at ThoughtWorks, a global IT services firm focused on end-to-end software delivery. She has worked extensively for large clients in the US, Canada, and China, delivering solutions for both disparate system delivery projects and agile enablement and organizational transformation efforts to incorporate and enhance efficiency and delivery processes. She is an author, mentor, coach and trainer of agile methodologies, processes, and practices. Tiffany is the author of Iteration Management Chapter in the ThoughtWorks anthology book and believes that the Iteration Manager's job is to build a well-oil delivery machine.""").save()

new Speaker(name:"Tim Berglund", title:"Developer, Consultant, Author", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/26273_Berglund_medium.jpg", bio:"""Tim Berglund runs a consulting firm called the August Technology Group, which provides training and development services to customers building web applications with open-source tools running on the JVM. He likes it best when these include Groovy and Grails.His technology interests span web applications, business integration, data architecture, and software architecture, but his greatest passion is to help developers improve in their craft. He is a speaker internationally and at conferences and user groups in the United States, and helps lead the Denver Open Source User Group.He lives in Littleton, CO with the wife of his youth and their three children.""").save()

new Speaker(name:"Venkat Subramaniam", title:"Founder of Agile Developer, Inc.", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/11_Subramaniam_medium.jpg", bio:"""Dr. Venkat Subramaniam, founder of Agile Developer, Inc., has trained and mentored thousands of software developers in the US, Canada, Europe, and Asia. Venkat helps his clients effectively apply and succeed with agile practices on their software projects, and speaks frequently at international conferences and user groups. He is author of ".NET Gotchas," coauthor of 2007 Jolt Productivity Award winning "Practices of an Agile Developer," author of "Programming Groovy: Dynamic Productivity for the Java Developer" and "Programming Scala: Tackle Multi-Core Complexity on the Java Virtual Machine" (Pragmatic Bookshelf).""").save()

new Speaker(name:"Vladimir Vivien", title:"Software Developer / Consultant / Author", imageUrl:"http://www.nofluffjuststuff.com/s/images/bio/2061_Vivien_medium.jpg", bio:"""Vladimir Vivien is a software engineer living in the United States. Past and current experiences include development in Java and C#.Net for industries including publishing, financial, and healthcare. He has a wide range of technology interests including Java, OSGi, Groovy/Grails, JavaFX, SunSPOT, BugLabs, module/component-based development, and anything else that runs on the JVM.Vladimir is the author of "JavaFX Application Development Cookbook" published by Packt Publishing. He is the creator of the Groovv JmxBuilder open source project, a JMX DSL, that is now part of the Groovy language. Other open source endeavor includes JmxLogger and GenShell. You can follow Vladimir through his blog: http://blog.vladimirvivien.com/, Twitter: http://twitter.com/vladimirvivien, and Linked In: http://www.linkedin.com/in/vvivien.""").save()

    }
    def destroy = {
    }
}
