import fluffbox.rwx.Store
import fluffbox.rwx.Kiosk
import fluffbox.rwx.Speaker
import fluffbox.rwx.SpeakerClone
import fluffbox.rwx.Role
import fluffbox.rwx.User
import fluffbox.rwx.UserRole

class BootStrap {

  def springSecurityService

  def init = { servletContext ->

    new Store(name: "Walgreens").save()
    new Kiosk(store: Store.findByName("Walgreens"), inside: true, address: "3895 W Broward Blvd",
            city: "Ft Lauderdale", state: "FL", zipCode: "33312-1017").save()
    new Store(name: "Winn Dixie").save()
    new Kiosk(store: Store.findByName("Winn Dixie"), inside: false, address: "1531 N State Road 7",
            city: "Lauderhill", state: "FL", zipCode: "33313-5807").save()
    new Kiosk(store: Store.findByName("Winn Dixie"), inside: false, address: "3800 N Ocean Blvd",
            city: "Fort Lauderdale", state: "FL", zipCode: "33308-6432").save()
    new Store(name: "Albertsons").save()
    new Kiosk(store: Store.findByName("Albertsons"), inside: true, address: "950 E Commercial Blvd",
            city: "Oakland Park", state: "FL", zipCode: "33334-3210").save()
    new Kiosk(store: Store.findByName("Walgreens"), inside: true, address: "601 E Commercial Blvd",
            city: "Oakland Park", state: "FL", zipCode: "33334-3239").save()
    new Store(name: "Walmart").save()
    new Kiosk(store: Store.findByName("Walmart"), inside: true, address: "3001 N State Rd 7",
            city: "Lauderdale Lakes", state: "FL", zipCode: "33313-1913").save()
    new Kiosk(store: Store.findByName("Winn Dixie"), inside: false, address: "3116 W Commercial Blvd",
            city: "Fort Lauderdale", state: "FL", zipCode: "33309-3415").save()
    new Store(name: "Walmart Neighborhood Markets").save()
    new Kiosk(store: Store.findByName("Walmart Neighborhood Markets"), inside: true, address: "1199 S Federal Hwy",
            city: "Pompano Beach", state: "FL", zipCode: "33062-7067").save()
    new Store(name: "Exxon Mobil").save()
    new Kiosk(store: Store.findByName("Exxon Mobil"), inside: true, address: "2399 S University Dr",
            city: "Davie", state: "FL", zipCode: "33324-5844").save()
    new Kiosk(store: Store.findByName("Walgreens"), inside: true, address: "3015 S University Dr",
            city: "Davie", state: "FL", zipCode: "33328-2013").save()
    new Kiosk(store: Store.findByName("Exxon Mobil"), inside: true, address: "1799 N University Dr",
            city: "Plantation", state: "FL", zipCode: "33322-4111").save()
    new Kiosk(store: Store.findByName("Walmart"), inside: true, address: "2300 W Atlantic Blvd",
            city: "Pompano Beach", state: "FL", zipCode: "33069-2655").save()
    new Kiosk(store: Store.findByName("Walgreens"), inside: true, address: "7105 W McNab Rd",
            city: "North Lauderdale", state: "FL", zipCode: "33068-5492").save()
    new Kiosk(store: Store.findByName("Walmart"), inside: true, address: "3306 N University Dr",
            city: "Sunrise", state: "FL", zipCode: "33351").save()
    new Kiosk(store: Store.findByName("Walmart"), inside: true, address: "7300 W McNab Rd",
            city: "North Lauderdale", state: "FL", zipCode: "33068-5481").save()
    new Kiosk(store: Store.findByName("Walmart"), inside: true, address: "1885 N Pine Island Rd",
            city: "Plantation", state: "FL", zipCode: "33322-5208").save()
    new Kiosk(store: Store.findByName("Walgreens"), inside: true, address: "6817 Taft St",
            city: "Hollywood", state: "FL", zipCode: "33024-5601").save()

    		new Speaker(name: "Craig Walls", title: "Author of Spring in Action", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/38_Walls_20110408_053039_medium_sq.jpg", bio: """Craig Walls has been professionally developing software for over 16 years (and longer than that for the pure geekiness of it). He is a senior engineer with SpringSource and is the author of Modular Java (published by Pragmatic Bookshelf) and Spring in Action and XDoclet in Action (both published by Manning). He's a zealous promoter of the Spring Framework, speaking frequently at local user groups and conferences and writing about Spring and OSGi on his blog. When he's not slinging code, Craig spends as much time as he can with his wife, two daughters, 5 birds and 3 dogs. """).save()
			new Speaker(name: "Venkat Subramaniam", title: "Founder of Agile Developer, Inc.", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/11_Subramaniam_20110408_052930_medium_sq.jpg", bio: """Dr. Venkat Subramaniam, founder of Agile Developer, Inc., has trained and mentored thousands of software developers in the US, Canada, Europe, and Asia. Venkat helps his clients effectively apply and succeed with agile practices on their software projects, and speaks frequently at international conferences and user groups. Venkat is also an adjunct faculty and teaches CS courses remotely at the University of Houston. He is author of ".NET Gotchas," coauthor of 2007 Jolt Productivity Award winning "Practices of an Agile Developer," author of "Programming Groovy: Dynamic Productivity for the Java Developer" and "Programming Scala: Tackle Multi-Core Complexity on the Java Virtual Machine" (Pragmatic Bookshelf). """).save()
			new Speaker(name: "Matt Stine", title: "Enterprise Java/Cloud Consultant", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/29510_Stine_20110511_093013_medium_sq.jpg", bio: """ Matt Stine is an Enterprise Java/Cloud consultant based in Memphis, TN. He is a twelve year veteran of the enterprise software and web development industries, with experience spanning the healthcare, biomedical research, e-commerce, and retail store domains. Matt has spoken at conferences ranging from JavaOne to CodeMash and has published several articles for Agile Zone, GroovyMag and NFJS the Magazine, as well as the Selenium 2.0 DZone Refcard. Matt is also the founder of the Memphis/Mid-South Java User Group. His current areas of interest include lean/agile software development, software architecture, mobile application development and functional languages.""").save()
			new Speaker(name: "Brian Sletten", title: "Forward Leaning Software Engineer", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/22_Sletten_20110408_052806_medium_sq.jpg", bio: """Brian Sletten is a liberal arts-educated software engineer with a focus on using and evangelizing forward-leaning technologies. He has a background as a system architect, a developer, a security consultant, a mentor, a team lead, an author and a trainer and operates in all of those roles as needed. His experience has spanned the online game, defense, finance, academic, hospitality, retail and commercial domains. He has worked with a wide variety of technologies such as network matrix switch controls, 3D simulation/visualization, Grid Computing, P2P and Semantic Web-based systems. He has a B.S. in Computer Science from the College of William and Mary. He is President of Bosatsu Consulting, Inc. and lives in Los Angeles, CA.  He focuses on web architecture, resource-oriented computing, social networking, the Semantic Web, scalable systems, security consulting and other technologies of the late 20th and early 21st Centuries. """).save()
			new Speaker(name: "Ken Sipe", title: "Gradleware CTO", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/4142_Sipe_20110408_052912_medium_sq.jpg", bio: """Ken Sipe is the CTO of Gradleware, Inc. (gradleware.com). With the co-founders Hans Dockter and Adam Murdoch, Ken helps companies of all sizes adopt agile practices and automate their enterprise systems enabling faster time to market and higher quality.  Ken has been a practitioner and instructor of RUP since the late 1990s, and an extreme programmer and coach since the middle 2000s. Ken has worked with Fortune 500 companies to small startups in the roles of developer, designer, application architect and enterprise architect. Ken's current focus is on enterprise system automation and continuous delivery systems.  Ken is an international speaker on the subject of software engineering speaking at conferences such as JavaOne, JavaZone, Jax-India, and The Strange Loop. He is a regular speaker with NFJS where he is best known for his architecture and security hacking talks. In 2009, Ken was honored by being awarded the JavaOne Rockstar Award at JavaOne in SF, California and the JavaZone Rockstar Award at JavaZone in Oslo, Norway as the top ranked speaker. """).save()
			new Speaker(name: "Nathaniel Schutta", title: "Author, speaker, software engineer focused on user interface design.", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/1314_Schutta_20110425_214233_medium_sq.jpg", bio: """Nathaniel T. Schutta is a senior software engineer focussed on making usable applications. A proponent of polyglot programming, Nate has written two books on Ajax and speaks regularly at various worldwide conferences, No Fluff Just Stuff symposia, universities, and Java user groups. In addition to his day job, Nate is an adjunct professor at the University of Minnesota where he teaches students to embrace dynamic languages. """).save()
			new Speaker(name: "Mark Richards", title: "SOA and Integration Architect, Author of Java Message Service", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/35_Richards_20110408_052602_medium_sq.jpg", bio: """Mark Richards is a Director and Senior Architect at Collaborative Consulting, LLC, a Boston-based Business and Architecture Consulting Firm, where he is involved in the architecture, design, and implementation of SOA, EDA, messaging, and other architectures, primarily in the Java platform. Prior to joining Collaborative Mark was an Executive IT Architect with IBM, where he worked as an SOA and enterprise architect in the financial services area. He has been involved in the software industry since 1984 and has many battle scars to show for it. Mark served as the President of the Boston Java User Group in 1997 and 1998, and the President of the New England Java Users Group from 1999 thru 2003. Mark is the author of the book Java Message Service (2nd edition) from O'Reilly. He is also the author of Java Transaction Design Strategies, contributing author of the book 97 Things Every Software Architect Should Know from O'Reilly, contributing author of NFJS Anthology Volume 1, and contributing author of NFJS Anthology Volume 2. Mark has many architect and developer certifications, including those from IBM, Sun, The Open Group, and Oracle. He is a regular conference speaker at the No Fluff Just Stuff Symposium Series and speaks at other conferences and user groups around the world. When he is not working Mark can usually be found hiking with his wife and two daughters in the White Mountains or along the Appalachian Trail. """).save()
			new Speaker(name: "Pratik Patel", title: "Enterprise Architect", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/14890_Patel_20110408_052535_medium_sq.jpg", bio: """Pratik Patel wrote the first book on 'enterprise Java' in 1996, "Java Database Programming with JDBC." He has also spoken at various conferences such as the Net Database Summit, WWW7 and the Atlanta Java User's Group (AJUG). Pratik currently runs the Atlanta Groovy and Grails User Group (ATL2G) as well as actively participating & presenting in the Atlanta Java UG.  Pratik's specialty is in large-scale Java applications for mission-critical use. He has designed and built enterprise applications in the retail, health care, financial services, and telecoms sectors. Pratik holds a master's in Biomedical Engineering from UNC, has worked in places such as New York, London, and Hong Kong, and currently lives in Atlanta, GA. """).save()
			new Speaker(name: "Ted Neward", title: "Enterprise, Virtual Machine and Language Wonk", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/9_Neward_20110408_052500_medium_sq.jpg", bio: """Ted Neward is the Principal with Neward & Associates, where he specializes in high-scale enterprise systems, working with clients ranging in size from Fortune 500 corporations to small 20-person shops. He speaks on the conference circuit, including the No Fluff Just Stuff Symposium tour, discussing Java, .NET and XML service technologies, focusing on Java-.NET interoperability, programming languages, and virtual machine technologies. He has written several widely-recognized books in both the Java and .NET space, including the recently-released "Effective Enterprise Java", and the forthcoming "Professional F#". He lives in the Pacific Northwest. """).save()
			new Speaker(name: "Matthew McCullough", title: "Open Source Architect, Ambient Ideas", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/9793_McCullough_20110408_052438_medium_sq.jpg", bio: """Matthew McCullough is an energetic 15 year veteran of enterprise software development, open source education, and co-founder of Ambient Ideas, LLC, a Denver consultancy. Matthew currently is a trainer for GitHub.com, author of the Git Master Class series for O'Reilly, speaker at over 30 national and international conferences, author of three of the top 10 DZone RefCards, and President of the Denver Open Source Users Group. His current topics of research center around project automation: build tools (Maven, Leiningen, Gradle), distributed version control (Git), Continuous Integration (Hudson) and Quality Metrics (Sonar). Matthew resides in Denver, Colorado with his beautiful wife and two young daughters, who are active in nearly every outdoor activity Colorado has to offer. """).save()
			new Speaker(name: "Neal Ford", title: "Application Architect at ThoughtWorks, Inc.", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/21_Ford_20110408_051758_medium_sq.jpg", bio: """Neal is Software Architect and Meme Wrangler at ThoughtWorks, a global IT consultancy with an exclusive focus on end-to-end software development and delivery. Before joining ThoughtWorks, Neal was the Chief Technology Officer at The DSW Group, Ltd., a nationally recognized training and development firm. Neal has a degree in Computer Science from Georgia State University specializing in languages and compilers and a minor in mathematics specializing in statistical analysis. He is also the designer and developer of applications, instructional materials, magazine articles, video presentations, and author of 6 books, including the most recent The Productive Programmer. His language proficiencies include Java, C#/.NET, Ruby, Groovy, functional languages, Scheme, Object Pascal, C++, and C. His primary consulting focus is the design and construction of large-scale enterprise applications. Neal has taught on-site classes nationally and internationally to all phases of the military and to many Fortune 500 companies. He is also an internationally acclaimed speaker, having spoken at over 100 developer conferences worldwide, delivering more than 600 talks. If you have an insatiable curiosity about Neal, visit his web site at http://www.nealford.com. He welcomes feedback and can be reached at nford@thoughtworks.com. """).save()
			new Speaker(name: "Jeff Brown", title: "Core Member of the Grails Development Team", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/4133_Brown_20110408_051527_medium_sq.jpg", bio: """Core member of the Grails development team, Jeff Brown, is a Senior Software Engineer with SpringSource. Jeff has been involved in designing and building object oriented systems for over 15 years. Jeff's areas of expertise include web development with Groovy & Grails, Java and agile development. """).save()
			new Speaker(name: "Tim Berglund", title: "Developer, Consultant, Author", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/26273_Berglund_20110408_051216_medium_sq.jpg", bio: """Tim is a full-stack generalist and passionate teacher who loves coding, presenting, and working with people. He believes the best developer is one who is well-informed of specifics and can also make deep connections between software development and the broader world. He has recently been exploring non-relational data stores, continuous deployment, and how software architecture should resemble an ant colony.  His firm, the August Technology Group, helps clients with product development, technology consulting, and technology upgrade projects atop the JVM. The August Group's technology preferences reflect the generalist sensibilities of its founder, and its development practices are always lightweight, self-improving, and humanizing by design.  Tim is a speaker internationally and on the No Fluff Just Stuff tour in the United States, and is co-president of the Denver Open Source User Group in the Denver area, co-author of the DZone Clojure RefCard, co-presenter of the best-selling O'Reilly Git Master Class, and co-author of a forthcoming series of ebooks on the next-generation build system, Gradle.  He lives in Littleton, CO with the wife of his youth and their three children. """).save()
			new Speaker(name: "Peter Bell", title: "Agile Architect", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/26712_Bell_20110408_051204_medium_sq.jpg", bio: """Peter presents internationally and writes extensively on domain specific languages, agile architecture, NoSQL and requirements and estimating. He helps teams to develop great software quickly by improving the requirements gathering, estimating, project management processes, engineering practices and tools used.  He specializes in "jump start" engagements, helping teams to improve their effectiveness by coaching and pairing with the team to find impediments and improve productivity. He also helps teams to understand and implement new technologies - from NoSQL data stores to language workbenches.  He is on the program committee for Code Generation in Cambridge, England and the Domain Specific Modeling workshop at SPLASH (was ooPSLA). He has presented at a range of conferences including ooPSLA, Code Generation, Practical Product Lines, the British Computer Society Software Practices Advancement conference and the No Fluff Just Stuff tour. He has been published in IEEE Software, Dr. Dobbs, Information Week, Methods & Tools, NFJS the Magazine and is a regular contributor to GroovyMag.  Peter is also the CEO/CTO of SystemsForge - a New York based company that uses DSLs and a Software Product Line built on top of Groovy and Grails to develop custom web applications quickly and cost effectively. The SystemsForge product line has been presented at ooPSLA and Code Generation and written up in IEEE Software and Methods & Tools. """).save()
			new Speaker(name: "Mark Volkmann", title: "Software Consultant and Partner at OCI", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/842_Volkmann_20110408_053025_medium_sq.jpg", bio: """Mark Volkmann has been a software consultant for Object Computing, Inc. (OCI) in St. Louis since 1996. He has been developing software in Java since 1995.  Mark has created and teaches many courses in Java, XML and Ruby. They include: Introduction to Java, Java Syntax for Non-C Programmers, Java Programming, Advanced Java Programming, Creating Graphical User Interfaces Using Java (Swing), eXtensible Markup Language (XML), XML Programming Using Java and Web Services Using Java, and Ruby Programming.  Mark is a member of the St. Louis Java User Group steering committee and a regular presenter for that group. He has written for XML Journal. Mark has also presented at XML DevCon conferences, No Fluff Just Stuff Java symposiums and the St. Louis Ruby User Group. """).save()
			new Speaker(name: "Vladimir Vivien", title: "Software Developer / Consultant / Author", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/2061_Vivien_20110408_053010_medium_sq.jpg", bio: """Vladimir Vivien is a software engineer living in the United States. Past and current experiences include development in Java and C#.Net for industries including publishing, financial, and healthcare. He has a wide range of technology interests including Java, OSGi, Groovy/Grails, JavaFX, SunSPOT, BugLabs, module/component-based development, and anything else that runs on the JVM.  Vladimir is the author of "JavaFX Application Development Cookbook" published by Packt Publishing. He is the creator of the Groovv JmxBuilder open source project, a JMX DSL, that is now part of the Groovy language. Other open source endeavor includes JmxLogger and GenShell. You can follow Vladimir through his blog: http://blog.vladimirvivien.com/, Twitter: http://twitter.com/vladimirvivien, and Linked In: http://www.linkedin.com/in/vvivien. """).save()
			new Speaker(name: "Burr Sutter", title: "Software Architect", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/526_Sutter_20110408_052954_medium_sq.jpg", bio: """Burr Sutter is a current Sun Java Champion, President of the Atlanta Java Users Group and President of the Atlanta Chapter of the International Association of Software Architects. He has over 15 years of software design and development experience along with numerous published articles, book chapters and developer conference speaking engagements. He is presently employed at JBoss, a division of Red Hat. """).save()
			new Speaker(name: "Srivaths Sankaran", title: "Sr. Java Consultant", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/20822_Sankaran_20110408_052737_medium_sq.jpg", bio: """Sri Sankaran has been professionally developing software for over 15 years. During this time, he has designed and delivered solutions for clients in industries as varied as insurance, energy, telecom and the retail sector. Leveraging the breadth of this experience along with the depth of his knowledge of pertinent technologies such as Spring, Hibernate, Ajax, Java and Ruby on Rails allows him to choose the right combination of tools and techniques to solve his customers divergent needs.  Over the years as a consultant he has been relied upon as the go-to person for matters of application architecture. Project managers look to his leadership and guidance in project estimation, staffing and delivery.  When he is not working on software he spends time with his family of wife, daughter and dog. Oh, he is a rabid dog lover and would love to one day have a pack of dogs and raise them to be well balanced therapy animals. """).save()
			new Speaker(name: "Brian Sam-Bodden", title: "Java author, Ruby geek and Open Source Advocate", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/28_Sam_Bodden_20110408_052712_medium_sq.jpg", bio: """Brian Sam-Bodden is an author, instructor, speaker and hacker that has spent over fifteen years crafting software systems. He holds dual bachelor degrees from Ohio Wesleyan University in computer science and physics and heads Integrallis http://www.integrallis.com. He is a frequent speaker at user groups and conferences nationally and abroad. Brian is the author of "Beginning POJOs: Spring, Hibernate, JBoss and Tapestry", co-author of the "Enterprise Java Development on a Budget: Leveraging Java Open Source Technologies" and a contributor to O'reilly's "97 Things Every Project Manager Should Know". """).save()
			new Speaker(name: "Johanna Rothman", title: "Speaker, Consultant, author for managing product development", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/15415_Rothman_20110408_052622_medium_sq.jpg", bio: """Johanna Rothman helps managers and leaders solve problems and seize opportunities.  She consults, speaks, and writes on managing high-technology product development. She enables managers, teams, and organizations to become more effective by applying her pragmatic approaches to the issues of project management, risk management, and people management.  Johanna writes two blogs: Managing Product Development and Hiring Technical People. She is the author of:  - Manage Your Project Portfolio: Increase Your Capacity and Finish More Projects. - 2008 Jolt Productivity award winning Manage It! Your Guide to Modern, Pragmatic Project Management - Behind Closed Doors: Secrets of Great Management (with Esther Derby) - Hiring the Best Knowledge Workers, Techies & Nerds: The Secrets and Science of Hiring Technical People  Find more of Johanna's articles and her blogs at www.jrothman.com. """).save()
			new Speaker(name: "Paul Rayner", title: "Agile Consultant, Developer and Architect for Virtual Genius LLC", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/15893_Rayner_20110408_052556_medium_sq.jpg", bio: """Paul Rayner is a Denver-based independent consultant with more than twenty years of software development and consulting experience. His company, Virtual Genius LLC, provides organizations with the tools and practices needed to succeed at agile software development, from portfolio management through to customer delivery. He specializes in helping organizations struggling with their transition to agile software development, or in need of external agile custom development and architectural expertise. Paul is an active member of the Colorado developer and agile communities, on the Agile Denver leadership team, a certified Domain-Driven Design instructor, a member of the Agile Cooperative, and a regular speaker at user groups and conferences. He writes with an Australian accent about software development at www.virtual-genius.com/blog """).save()
			new Speaker(name: "Howard Lewis Ship", title: "Creator of Apache Tapestry", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/31_Lewis_Ship_20110408_052337_medium_sq.jpg", bio: """Howard Lewis Ship is the creator and lead developer for the Apache Tapestry project, and is a noted expert on Java framework design and developer productivity. He has over twenty years of full-time software development under his belt, with over ten years of Java. He cut his teeth writing customer support software for Stratus Computer, but eventually traded PL/1 for Objective-C and NeXTSTEP before settling into Java.  Howard is respected in the Java community as an expert on web application development, dependency injection, Java meta-programming, and developer productivity. He is a frequent speaker at JavaOne, NoFluffJustStuff, ApacheCon and other conferences, and the author of "Tapestry in Action" for Manning (covering Tapestry 3.0). Lately, he's been dipping his toes into alternate languages, including Clojure.  Howard is an independent consultant, offering Tapestry training, mentoring and project work as well as training in Clojure. He lives in Portland, Oregon with his wife Suzanne, and his son, Jacob. """).save()
			new Speaker(name: "Tiffany Lentz", title: "Principal Consultant & Program Manager with Thoughtworks", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/29664_Lentz_20110408_053802_medium_sq.jpg", bio: """Tiffany Lentz, a Principal Consultant and Program Manager, is proudly employed at ThoughtWorks, a global IT services firm focused on end-to-end software delivery. She has worked extensively for large clients in the US, Canada, and China, delivering solutions for both disparate system delivery projects and agile enablement and organizational transformation efforts to incorporate and enhance efficiency and delivery processes. She is an author, mentor, coach and trainer of agile methodologies, processes, and practices. Tiffany is the author of Iteration Management Chapter in the ThoughtWorks anthology book and believes that the Iteration Manager's job is to build a well-oil delivery machine. """).save()
			new Speaker(name: "Scott Leberknight", title: "Chief Architect at Near Infinity", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/646_Leberknight_20110408_052242_medium_sq.jpg", bio: """Scott is Chief Architect at Near Infinity Corporation, an enterprise software development and consulting services company based in Reston, Virginia. He has been developing enterprise and web applications for 14 years professionally, and has developed applications using Java, Ruby, Groovy, and even an iPhone application with Objective-C. His main areas of interest include alternative persistence technologies, object-oriented design, system architecture, testing, and frameworks like Spring, Hibernate, and Ruby on Rails. In addition, Scott enjoys learning new languages to make himself a better and more well-rounded developer a la The Pragmatic Programmers' advice to "learn one language per year."  Scott holds a B.S. in Engineering Science and Mechanics from Virginia Tech, and an M. Eng. in Systems Engineering from the University of Maryland. Scott speaks at the No Fluff Just Stuff Symposiums and various other conferences. In his (sparse) spare time, Scott enjoys spending time with his wife, three children, and cat. He also tries to find time to play soccer, go snowboarding, and mountain bike whenever he can. """).save()
			new Speaker(name: "Kenneth Kousen", title: "President of Kousen IT, Inc.", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/848_Kousen_20110408_052155_medium_sq.jpg", bio: """Ken Kousen is the President of Kousen IT, Inc., through which he does technical training, mentoring, and consulting in all areas of Java and XML. He is the author of the upcoming book about Java/Groovy integration, entitled "Making Java Groovy", from Manning.  He has been a tech reviewer for several books on software development. Over the past decade he's taught thousands of developers in business and industry. He is also an adjunct professor at the Rensselaer Polytechnic Institute site in Hartford, CT. His academic background includes two BS degrees from M.I.T., an MS and a Ph.D. from Princeton, and an MS in Computer Science from R.P.I. """).save()
			new Speaker(name: "Dave Klein", title: "Author of 'Grails: A Quick-Start Guide'", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/2412_Klein_20110408_052144_medium_sq.jpg", bio: """Dave is a consultant helping organizations of all sizes to develop applications more quickly (and have more fun doing it) with Grails. Dave has been involved in enterprise software development for the past 15 years. He has worked as a developer, architect, project manager, mentor and trainer. Dave has presented at user groups and national conferences. He is also the founder of the Capital Java User Group in Madison, Wisconsin, the Gateway Groovy Users in St. Louis, MO, and the author of Grails: A Quick-Start Guide, published by the Pragmatic Programmers. . Dave's Groovy and Grails related thoughts can be found at http://dave-klein.blogspot.com """).save()
			new Speaker(name: "Mark Johnson", title: "Staff System Engineer @ VMware", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/2816_Johnson_20110408_052126_medium_sq.jpg", bio: """Mark Johnson is a Staff System Engineer at VMware where he focuses on helping people learn more about SpringSource technologies and they can aid enterprise applications.  Mark has worked on a wide range of technology during his career. Most recently he has focused on Groovy, Grails, and Scala as technologies which enable high quality applications quickly.  Mark is active in the software community as the President of the New England Java Users Group (NEJUG) and a regular presenter to user groups and various conferenes. When not working, Mark can be found riding his mountain bike on local trails and playing with his family """).save()
			new Speaker(name: "David Hussman", title: "Agility Coach/Instructor/Practioner", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/23_Hussman_20110408_052027_medium_sq.jpg", bio: """David teaches and coaches the adoption and improvement of agility as a delivery tool. His work includes helping companies of all sizes all over the world. Sometimes he is pairing with developers and testers, while other times he is helping to invent, evolve and plan the delivery of all types of products and projects. David also spends a great deal of time helping leaders at all levels find ways to pragmatically use agility to foster innovation.  Prior to working as a full time coach, David spent years building software in a variety of domains: digital audio, digital biometrics, medical, financial, retail, and education to name a few. David now leads DevJam, a company composed of agile collaborators. As mentors and practitioners, DevJam focuses on agility as a tool to help people and companies improve their software production skills. DevJam provides seasoned leaders that strive to pragmatically match technology, people, and processes to create better and cooler products in competitive cycles.  Along with teaching and coaching, David participates in conferences around the world. He is the recipient of the Agile Alliance, 2009 Gordon Pask Award. David continuously contributes to books and various publications.  For coaching information, presentations, and more, visit www.devjam.com """).save()
			new Speaker(name: "Erik Hatcher", title: "co-author of \"Lucene in Action\"", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/43410_Hatcher_20110408_052004_medium_sq.jpg", bio: """Erik Hatcher is the co-author of "Lucene in Action" as well as co-author of "Java Development with Ant". Erik has been an active member of the Lucene community - a leading Lucene and Solr committer, member of the Lucene Project Management Committee, member of the Apache Software Foundation as well as a frequent invited speaker at various industry events. Erik co-founded Lucid Imagination, and is a member of its technical staff. """).save()
			new Speaker(name: "Hamlet D`Arcy", title: "Sr. Java/Groovy Developer, Groovy Committer", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/29441_D_Arcy_20110408_051748_medium_sq.jpg", bio: """Hamlet D'Arcy has been writing software for over a decade, and has spent considerable time coding in C++, Java, and Groovy. He's passionate about learning new languages and different ways to think about problems, and recently he's been discovering the joys of both F# and Scheme. He's an active member of the Groovy Users of Minnesota and the Object Technology User Group, is a committer on the Groovy project and CodeNarc, and is a contributor on a few open source projects (including JConch and the IDEA Groovy Plugin). He blogs regularly at http://hamletdarcy.blogspot.com and can be found on Twitter as HamletDRC (http://twitter.com/hamletdrc). """).save()
			new Speaker(name: "Keith Donald", title: "SpringSource Principal & Founding Partner", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/27_Donald_20110408_051725_medium_sq.jpg", bio: """Keith Donald is a principal and founding partner at SpringSource, the company behind Spring and a division of VMware. At SpringSource, Keith is a full-time member of the Spring development team focusing on web application development productivity. He is also the architect behind SpringSource's state-of-the-art training curriculum, which has provided practical Spring training to over 10,000 students worldwide.  Over his career, Keith, an experienced enterprise software developer and mentor, has built business applications for customers spanning a diverse set of industries including banking, network management, information assurance, education, retail, and healthcare. He is particularly skilled at translating business requirements into technical solutions. """).save()
			new Speaker(name: "Hans Dockter", title: "Founder of Gradle and CEO of Gradleware", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/29446_Dockter_20110408_051916_medium_sq.jpg", bio: """Hans Dockter is the founder and project lead of the Gradle build system and the CEO of Gradleware, a company that provides training, support and consulting for Gradle and all forms of enterprise software project automation in general.  Hans has 13 years of experience as a software developer, team leader, architect, trainer, and technical mentor. Hans is a thought leader in the field of project automation and has successfully been in charge of numerous large-scale enterprise builds. He is also an advocate of Domain Driven Design, having taught classes and delivered presentations on this topic together with Eric Evans. In the earlier days, Hans was also a committer for the JBoss project and founded the JBoss-IDE. """).save()
			new Speaker(name: "Esther Derby", title: "Co-author of \"Behind Closed Doors: Secrets of Great Management\"", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/15419_Derby_20110408_051653_medium_sq.jpg", bio: """Esther works with individuals, teams, and managers to improve their ability to deliver valuable software. Esther is recognized as a leader in the human-side of software development, including management, systems-thinking, organizational change, collaboration, team building, facilitation and retrospectives.  She?s been a programmer, system manager, manager and internal consultant. Since 1997, she?s run her own consulting firm, esther derby associates, inc., in Minneapolis, MN. Her clients include small niche firms, mid-size companies and Fortune 500 companies. She?s worked in financial services, insurance, health care and manufacturing as well as in product and software-as-a-service companies.  Esther is the author of over 100 articles, and co-author of Agile Retrospectives: Making Good Teams Great and Behind Closed Doors: Secrets of Great Management. She?s written widely on the topic of management, leadership, collaboration and change as they relate to companies adopting (or considering) Agile Methods, including Three Pillars of Executive Support for Agile Adoption (Agile Journal), Achieving Agility: Means to an End or End in Itself? (insights), and What?s a Manager to Do? (Better Software Magazine).  Esther is a sought after teacher and speaker. She?s given talks and workshops in the US, Europe, China, India, and New Zealand.  She?s a founder of the AYE Conference, and is serving her second term as a member of the Board of Directors for the Agile Alliance. She also was one of the three original founders of the Scrum Alliance.  Esther has an MA in Organizational Leadership and a certificate in Human System Dynamics.  Esther can be reached at (612) 724-8114, or by email.  Take a look at www.estherderby.com for more of Esther?s writing, or follow her on Twitter @estherderby """).save()
			new Speaker(name: "Jeremy Deane", title: "Director of Research & Architecture", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/20924_Deane_20110408_051639_medium_sq.jpg", bio: """Jeremy Deane has over 15 years of software engineering experience in leadership positions. His expertise includes Enterprise Integration Architecture, Web Application Architecture, and Software Process Improvement. In addition, he is an accomplished speaker and technical author. """).save()
			new Speaker(name: "James Carr", title: "Software Craftsman", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/4170_Carr_20110408_051556_medium_sq.jpg", bio: """James is a contractor in the St.Louis area that shares a passion for software craftsmanship and has enjoyed software development since he wrote his first program in Basic on the Tandy Color Computer 3 way back in 1988.  In addition to a passion for technology, he also has a keen interest in improving teamwork and collaboration through interactive activities to get people thinking creatively and develop stronger, richer communication channels with their stakeholders. """).save()
			new Speaker(name: "David Bock", title: "Principal Consultant, CodeSherpas Inc.", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/34_Bock_20110408_053548_medium_sq.jpg", bio: """ David Bock is a Principal Consultant at CodeSherpas, a company he founded in 2007. Mr. Bock is also the President of the Northern Virginia Java Users Group, the Editor of O'Reilly's OnJava.com website, and a frequent speaker on technology in venues such as the No Fluff Just Stuff Software Symposiums.   In January 2006, Mr. Bock was honored by being awarded the title of Java Champion by a panel of esteemed leaders in the Java Community in a program sponsored by Sun. There are approximately 100 active Java Champions worldwide.   David has also served on several JCP panels, including the Specification of the Java 6 Platform and the upcoming Java Module System.  In addition to his public speaking and training activities, Mr. Bock actively consults as a software engineer, project manager, and team mentor for commercial and government clients.  """).save()
			new Speaker(name: "Dan Allen", title: "Senior Software Engineer", imageUrl: "http://www.nofluffjuststuff.com/s/images/bio/5206_Allen_20110408_050959_medium_sq.jpg", bio: """Dan Allen is a member of the Seam and Web Beans project teams at JBoss by Red Hat, author of Seam in Action and a frequent speaker at major industry conferences such as JavaOne, Devoxx, TSSJS, Jazoon and JSFOne. Dan is known for his passionate work, with nearly a decade of development experience using technologies that include Java frameworks (Seam, JSF, EJB3, Hibernate, Spring, Struts), testing frameworks (JUnit, TestNG), JavaScript and DOM scripting, CSS and page layouts, Maven 2, Ant, Groovy, and many others.  Quickly after graduating from college, Dan became captivated by the world of free and open source software (FOSS). His involvment in FOSS helped him transition into the software development industry. He soon discovered the combination of Linux and the Java EE platform to be the ideal blend on which to build his professional career. In his search for a robust Web framework, Dan discovered JBoss Seam, which was quickly granted this most coveted spot in his development toolbox. The rest, as they say, is history. Dan is also a dedicated open source and Linux advocate and blogs about his experiences regularly. You can keep up with his discoveries by subscribing to his blog at http://mojavelinux.com. """).save()
			
    new SpeakerClone(speaker: Speaker.get(1), kiosk: Kiosk.get(1)).save()
    new SpeakerClone(speaker: Speaker.get(2), kiosk: Kiosk.get(1)).save()
    new SpeakerClone(speaker: Speaker.get(3), kiosk: Kiosk.get(1)).save()
    new SpeakerClone(speaker: Speaker.get(4), kiosk: Kiosk.get(1)).save()
    new SpeakerClone(speaker: Speaker.get(5), kiosk: Kiosk.get(1)).save()
    new SpeakerClone(speaker: Speaker.get(6), kiosk: Kiosk.get(1)).save()
    new SpeakerClone(speaker: Speaker.get(7), kiosk: Kiosk.get(1)).save()
    new SpeakerClone(speaker: Speaker.get(8), kiosk: Kiosk.get(1)).save()

    new SpeakerClone(speaker: Speaker.get(1), kiosk: Kiosk.get(2)).save()
    new SpeakerClone(speaker: Speaker.get(2), kiosk: Kiosk.get(2)).save()
    new SpeakerClone(speaker: Speaker.get(3), kiosk: Kiosk.get(2)).save()
    new SpeakerClone(speaker: Speaker.get(4), kiosk: Kiosk.get(2)).save()
    new SpeakerClone(speaker: Speaker.get(5), kiosk: Kiosk.get(2)).save()
    new SpeakerClone(speaker: Speaker.get(6), kiosk: Kiosk.get(2)).save()
    new SpeakerClone(speaker: Speaker.get(7), kiosk: Kiosk.get(2)).save()
    new SpeakerClone(speaker: Speaker.get(8), kiosk: Kiosk.get(2)).save()

    def customerRole = new Role(authority: 'ROLE_CUSTOMER').save(flush: true)

    String password = springSecurityService.encodePassword('password')
    def testUser = new User (username: 'joeuser', enabled: true, password: password, email: 'joeuser@fakemail.com')
    testUser.save (flush: true)

    UserRole.create testUser, customerRole, true
  }
  def destroy = {
  }
}
